config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'events#index'
  get 'static_pages/index'
  devise_for :users
  resources :users, only: [:show]
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord

    has_many :attendances
    has_many :users, through: :attendances
    belongs_to :organizer, class_name: "User"
  
    validates :start_date,
              presence: true
  
    validates :duration,
              presence: true,
              numericality: { greater_than: 0, Integer: true }
  
    validates :title,
              presence: true,
              length: { minimum: 5, maximum: 140 }
  
    validates :description,
              presence: true,
              length: { minimum: 20, maximum: 1000 }
  
    validates :price,
              presence: true,
              :inclusion => 1..1000,
              numericality: { greater_than: 0, Integer: true }
  
    validates :location,
              presence: true
  
    validate :start_must_be_before_end 
  
    validate :is_even_and_divisible_by_five?
  
    def start_must_be_before_end
      errors.add(:start_date, "The start date must be before end date") unless
        start_date > Time.now
    end
  
    def is_even_and_divisible_by_five?
      errors.add(:duration, "The duration must be a multiple of 5") unless
        duration % 5 == 0
    end
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances
  has_many :events, through: :attendances
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?

    def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new("start_date" => params[:start_date],
                              "duration" => params[:duration],
                              "title" => params[:title],
                              "description" => params[:description],
                              "location" => params[:location],
                              "price" => params[:price],
                              "organizer_id" => current_user.id)

      if @event.save
        redirect_to 'root_path'

      else
        render 'new'
  end

  def show
    @event = current_event
  end

end

private

  def current_event
    Event.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
    include EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def current_event
        Event.find(params[:id])
    end  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="jumbotron">
  <div class="container">
  <center>
    <h1>Voici les prochains évènements</h1>
  </div>
</div>

 <div class="row justify-content-center">
    <% @events.each do |event| %>
      <div class="card m-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= event.title %></h5>
          <p class="card-location"><%= event.location %></p>
          <%= link_to "See the full event", event_path(event.id), :class => "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
  </head>
  <body>
    <br>
    <h1 class="text-center"> Création d'un évènement</h1>
    <br>
    <br>
    <br>
    <div class="d-flex justify-content-center align-items-center container ">
      <div class="row ">
        <%= form_tag url_for(action: 'create'), method: "post" do %>
          <form action="">
            <div class="form-group">
              <%= label_tag 'Titre' %> <br />
              <%= text_field_tag 'title', @event.title, class: "form-control", placeholder: 'Titre', autocomplete: 'off' %>
            </div>
            <div class="form-group">
              <%= label_tag 'Description' %> <br />
              <%= text_field_tag 'description', @event.description, class: "form-control", placeholder: '20 a 1000 caractéres', autocomplete: 'off'%>
            </div>
            <div class="form-group">
              <%= label_tag 'Date de depart' %> <br />
              <%= text_field_tag 'start_date', @event.start_date, class: "form-control", placeholder: 'Date de debut', autocomplete: 'off'%>
            </div>
            <div class="form-group">
              <%= label_tag 'Durée' %> <br />
              <%= text_field_tag 'duration', @event.duration, class: "form-control", placeholder: 'tranches de 5 min', autocomplete: 'off'%>
            </div>
            <div class="form-group">
              <%= label_tag 'Prix entrée' %> <br />
              <%= text_field_tag 'price', @event.price, class: "form-control", placeholder: 'Prix €', autocomplete: 'off'%>
            </div>
            <div class="form-group">
              <%= label_tag 'Lieux' %> <br />
              <%= text_field_tag 'location', @event.location, class: "form-control", placeholder: 'Ville', autocomplete: 'off'%>
            </div>
            <%= submit_tag "Créer l'évènement", class: "btn btn-info" %>  <%= link_to "Revenir à l'accueil", root_path, :class => 'btn btn-secondary'%>
          </form>
        <% end%>
      </div>
    </div>
  </body>
</html>

app/views/events/show.html.erb
<br/><br><br>
<center>
<h1> Oh le bel évènement ! <h1/>
<div class="row justify-content-center">
      <div class="card m-3" style="width: 30rem;">
        <div class="card-body">
        <h5> <%= current_event.title %></h5>
        <br/>
        <h6> <%= current_event.description %></h6>
        <br/>
        <h6> <%= current_event.location %></h6>
        <h6> <%= current_event.duration %> minutes </h6>
        <h6> <%= current_event.price %> $ </h6>
        <h6> <%= current_event.organizer %> </h6>
          
        </div>
     </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbriteappfinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "Eventbrite App", root_path %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href=<%= new_event_path %>>Créer un nouvel évènement</a>
        </div>

      
      <% if user_signed_in? %>

        <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profil
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href=<%= users_show_path %>> Mon profil </a>
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class => "dropdown-item" %>
        </div>
      </div>

      <% else %>

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profil
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href=<%= new_user_registration_path %>>Inscription</a>
          <a class="dropdown-item" href=<%= new_user_session_path %>>Se connecter</a>
        </div>
      </div>

      <%end%>

    </nav>

    

    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

    <% if session[:success] %>
      <div class="alert alert-success" role="alert">
        <%= session[:success] %>
        <% session.delete(:success) %>
      </div>


    <% end %>



    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/users/show.html.erb
<center>
<h1> Mon profil </h1>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5> <%= current_user.first_name %> </h5>
    <p> <%= current_user.description %> </p>
    <%= link_to "Editer mon profil", edit_user_registration_path, :class => "btn btn-primary" %>
  </div>
</div>